// Generated by Carch IDL Compiler
// Source: examples/basic.carch
// Do not edit manually

#pragma once

#include <cstdint>
#include <string>
#include <variant>
#include <optional>
#include <vector>
#include <unordered_map>

namespace game {

// Person component with id, name, and age
struct Person {
    uint64_t id;
    std::string name;
    uint32_t age;
};

// Compact form (equivalent to above)
struct PersonCompact {
    uint64_t id;
    std::string name;
    uint32_t age;
};

// Gender enumeration
enum class Gender {
    male,
    female,
    other
};

// Contact information using variant (OR logic)
struct Contact_email { std::string value; };
struct Contact_phone { std::string value; };
struct Contact_address {
    std::string street;
    std::string city;
    std::string postal_code;
    std::string country;
};
using Contact = std::variant<Contact_email, Contact_phone, Contact_address>;

// Position component with 3D coordinates
struct Position {
    float x;
    float y;
    float z;
};

// Velocity component
struct Velocity {
    float dx;
    float dy;
    float dz;
};

// Health component
struct Health {
    uint32_t current;
    uint32_t max;
};

// Simple tag component (unit type in struct)
struct Marker {
    struct {} tag;
};

// Rarity enum for items
enum class Rarity {
    common,
    uncommon,
    rare,
    epic,
    legendary
};

// Compact syntax examples
enum class Direction {
    north,
    south,
    east,
    west
};

enum class Team {
    red,
    blue,
    green
};

struct State_idle {};
struct State_running {};
struct State_jumping {};
using State = std::variant<State_idle, State_running, State_jumping>;

} // namespace game
