// Generated by Carch IDL Compiler
// Source: examples/game_entities.carch
// Do not edit manually
// This is a placeholder - run with UPDATE_GOLDEN=1 to generate actual golden file

#pragma once

#include <cstdint>
#include <string>
#include <variant>
#include <optional>
#include <vector>
#include <unordered_map>

namespace game {

// Placeholder for golden file
// Run the test suite with UPDATE_GOLDEN=1 environment variable to generate

} // namespace game
